swagger: "2.0"
info: 
  title: Api yessss
  description: Api yessss
  version: "1.0.0"
  contact:
    name: "Aziz Matyakubov"
    email: "a.matyaqubov1471@gmail.com"
    url: "linkedin.com/in/aziz-matyakubov-1a1a6b1b3"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
  servers:
    - url: "http://localhost:3000"
      description: "Local server"
    - url: "https://api.yessss.com"
      description: "Production server"
host: "localhost:3000"
basePath: /api/v1/
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
 
  #return array of all users
  /users:
    get:
      summary: Get all users
      description: Get all users
      tags:
        - Users
      responses:
        200: 
          description: Success
          schema:
            type: array
            items:
              type: object
              properties:
                id: 
                  type: integer
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                img: 
                  type: string
                role:
                  type: string
                position:
                  type: string
                department:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
                    employees: 
                    # Employess is array and includes users id
                      type: array
                      items:
                        type: string
                      


                      
                    
                        








        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
        500:
          description: Internal server error
    
  #return user by id
  /users/{id}:
    get:
      summary: Get user by id
      description: Get user by id
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: User id
          required: true
          type: string
      responses:
        200: 
          description: Success
          schema:
            type: object
            example: Fake data


