swagger: "2.0"
info: 
  title: REST API
  description: This is a REST API for the application. It uses json web tokens for authentication. Refresh tokens are used to get new access tokens. 
  version: "1.0.0"
  contact:
    name: "Aziz Matyakubov"
    email: "a.matyaqubov1471@gmail.com"
    url: "https://www.linkedin.com/in/azizmatyakubov/"

host: "https://companyserver.onrender.com"
basePath: /api/v1/
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  # auth login
  /auth/login:
    post:
      # send email and password in body
      tags:
        - Auth
      summary: Login
      description: Login
      operationId: Login
      parameters:
        - name: body
          in: body
          description: Login
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
            example:
              email: "test@gmail.com"
              password: password
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Invalid input"
        401:
          description: "Unauthorized"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
  
  # auth register
  /auth/register:
    post:
      tags:
        - Auth
      summary: "Sign up"
      description: "In this method you can sign up. You need to send name, surname, email and password in body. Except password all fields are required. If there is no password, app will use default password. Default password is 'password'"
      operationId: "SignUp"
      parameters:
        - name: body
          in: body
          description: Login
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              surname:
                type: string
              email:
                type: string
              password:
                type: string
            
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Invalid input"
        401:
          description: "Unauthorized"
        404:
          description: "Not found"
        500:
          description: "Internal server error"

  # auth refresh
  /auth/refresh:
    get:
      tags:
        - Auth
      summary: "Refresh token"
      description: "Refresh token"


  # auth logout
  /auth/logout:
    get:
      tags:
        - Auth
      summary: "Logout"
      description: "This method is used to logout. You need to send refresh token in cookie. You will get 200 status code. After that, refresh token will be deleted from database"
      operationId: "Logout"
      parameters:
        - name: cookie
          in: cookie
          description: "Refresh token"
          required: true
          type: string
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Invalid input"
        401:
          description: "Unauthorized"
        404:
          description: "Not found"
        500:
          description: "Internal server error"

  # auth get me
  /auth/me:
    get:
      tags:
        - Auth
      summary: "Get me"
      description: "This method is used to get user info. You need to send access token in header. App will decode access token and get user id. After that, app will get user info from database"
      operationId: "GetMe"
      security:
        - JWT: []
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Invalid input"
        401:
          description: "Unauthorized"
        404:
          description: "Not found"
        500:
          description: "Internal server error"


  ### users
  /users:
    get:
      security:
        - JWT: []
      tags:
        - Users
      summary: "Get all users"
      description: "Get all users"
      operationId: "getUsers"
      
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Invalid input"
        401:
          description: "Unauthorized"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
    
  /users/{id}:
    get:
      summary: Get user by id
      description: This method is used to get user by id. You need to send access token in header and user id in url. Role of user must be admin or user must be owner of this user. 
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: User id that you want to get
          required: true
          type: string

      security:
        - JWT: []
        
      responses:
        200: 
          description: Success
          schema:
            type: object
            properties:
              id: 
                type: integer
              name:
                type: string
              surname:
                type: string
              email:
                type: string
              img: 
                type: string
              role:
                type: string
              position:
                type: string
              department:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  employees: 
                  # Employess is array and includes users id
                    type: array
                    items:
                      type: string

        400:
          description: Bad request
    put:
      summary: Update user by id
      description: This method is used to update user by id. You need to send access token in header and user id in url. Role of user must be admin or user must be owner of this user. You can update name, surname, email. 
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: User id
          required: true
          type: string  

        - name: body
          in: body
          description: User info
          type: object
          properties:
            name:
              type: string
            surname:
              type: string
            email:
              type: string        
      security:
        - JWT: []

      responses:
        200: 
          description: Success
          schema:
            type: object
            properties:
              id: 
                type: integer
              name:
                type: string
              surname:
                type: string
              email:
                type: string
              img: 
                type: string
              role:
                type: string
              position:
                type: string
              department:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  employees: 
                  # Employess is array and includes users id
                    type: array
                    items:
                      type: string

        400:
          description: Bad request
    delete:
      summary: Delete user by id
      description: This method is used to delete user by id. You need to send access token in header and user id in url. Role of user must be admin.
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: User id
          required: true
          type: string

      security:
        - JWT: []
      responses:
        200: 
          description: Success
          schema:
            type: object
            properties:
              id: 
                type: integer
              name:
                type: string
              surname:
                type: string
              email:
                type: string
              img: 
                type: string
              role:
                type: string
              position:
                type: string
              department:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  employees: 
                  # Employess is array and includes users id
                    type: array
                    items:
                      type: string

        400:
          description: Bad request
    
      summary: countUsers 
      description: countUsers
      tags:
        - Users
      parameters:
        - name: Authorization
          in: header
          description: User token
          required: true
          type: string

  /users/role/{role}:
    put:
      summary: Update user role by id
      description: This method is used to update user role by id. You need to send access token in header and user id in url. Role of user must be admin. 
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: User id
          required: true
          type: string  

        - name: body
          in: body
          description: User info
          type: object
          properties:
            role:
              type: string
      security:
        - JWT: []

      responses:
        200: 
          description: Success
          schema:
            type: object
            properties:
              id: 
                type: integer
              name:
                type: string
              surname:
                type: string
              email:
                type: string
              img: 
                type: string
              role:
                type: string
              position:
                type: string
              department:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  employees: 
                  # Employess is array and includes users id
                    type: array
                    items:
                      type: string

        400:
          description: Bad request

  /users/department/{id}:
    put:
      summary: Change department of user
      description: This method is used to change department of user. You need to send access token in header, user id in url and department name in body. Role of user must be admin. Departments ["HR", "Marketing", "Sales"]
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: User id
          required: true
          type: string  

        - name: body
          in: body
          description: Department name
          type: object
          properties:
            department:
              type: string
          example:
            department: "HR"

      security:
        - JWT: []
        
      responses:
        200: 
          description: Success
          schema:
            type: array
            items:
              type: object
              properties:
                id: 
                  type: integer
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                img: 
                  type: string
                role:
                  type: string
                position:
                  type: string
                department:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
                    employees: 
                    # Employess is array and includes users id
                      type: array
                      items:
                        type: string

        400:
          description: Bad request

  /users/countUsers:
    get:
      summary: countUsers 
      description: This method is used to count users. You need to send access token in header.
      tags:
        - Users
      security:
        - JWT: []
      responses:
        200: 
          description: Success
          schema:
            type: object
            properties:
              count:
                type: integer
        400:
          description: Bad request

  /users/avatar/{id}:
    post:
      summary: Update user avatar
      description: This method is used to update user avatar. You need to send access token in header and image in body.
      tags:
        - Users
      consumes:
        - multipart/form-data
      parameters:
        - name: id
          in: path
          description: User id
          required: true
          type: string

        - name: avatar
          in: formData
          description: User avatar
          required: true
          type: file

      security:
        - JWT: []


      responses:  
        200: 
          description: Success
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error

  /users/csv:
    get:
      summary: Download CSV
      description: This method is used to download CSV file. You need to send access token in header. Only admin can download CSV file.
      tags:
        - Users
      security:
        - JWT: []

      responses:
        200: 
          description: Success
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error

  ### departments
  /departments:
    post:
      tags:
        - Departments
      summary: "Create department"
      description: "This method is used to create department. You need to send access token in header, department name and department description in body. Role of user must be admin."
      parameters:
        - name: body
          in: body
          description: Department info
          type: object
          properties:
            name:
              type: string
            description:
              type: string
          example:
            name: "HR"
            description: "Human resources"
      security:
        - JWT: []
      responses:
        200: 
          description: Success
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error
    get: 
      tags:
        - Departments
      summary: "Get all departments"
      description: "This method is used to get all departments. You need to send access token in header. Role of user must be admin or user."
      security:
        - JWT: []
      responses:
        200: 
          description: Success
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error

  /departments/{id}:
    get:
      summary: Get department by id
      description: This method is used to get department by id. You need to send access token in header. Role of user must be admin or user.
      tags:
        - Departments
      parameters:
        - name: id
          in: path
          description: Department id
          required: true
          type: string
      security:
        - JWT: []
      responses:
        200: 
          description: Success
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error
    put:
      summary: Update department by id
      description: This method is used to update department by id. You need to send access token in header, department id in url and department name and/or department description in body. Role of user must be admin.
      tags:
        - Departments
      parameters:
        - name: id
          in: path
          description: Department id
          required: true
          type: string

        - name: body
          in: body
          description: Department info
          type: object
          properties:
            name:
              type: string
            description:
              type: string
          example:
            name: "HR"
            description: "Human resources"
      security:
        - JWT: []
        
      responses:
        200: 
          description: Success
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error
    delete:
      summary: Delete department by id
      description: Delete department by id
      tags:
        - Departments
      parameters:
        - name: id
          in: path
          description: Department id
          required: true
          type: string
      security:
        - JWT: []
      responses:
        200: 
          description: Success
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error

  /departments/search:
    get:
      summary: Search department by name
      description: Search department by name
      tags:
        - Departments
      parameters:
        - name: name
          in: query
          description: Department name
          required: true
          type: string

        - name: Authorization
          in: header
          description: User token
          required: true
          type: string
      responses:
        200: 
          description: Success
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              description:
                type: string
              employees: 
              # Employess is array and includes users id
                type: array
                items:
                  type: string

        400:
          description: Bad request

# JWT token
securityDefinitions:
  JWT:
    type: apiKey
    name: Authorization
    in: header


### definitions
definitions:
  User:
    properties:
      id:
        type: integer
      name:
        type: string
      surname:
        type: string
      email:
        type: string
      password:
        type: string
      img:
        type: string
      role:
        type: string
      position:
        type: string
      department:
        type: integer
        description: Department id
      refreshToken:
        type: string
    
  Department:
    properties:
      id:
        type: integer
      name:
        type: string
      description:
        type: string
      employees: 
      # Employess is array and includes users id
        type: array
        items:
          type: string
    
 